PROGS = standard_tentative
SRCS_standard_tentative = standard_tentative.cc
MAN =

CXX = clang++-17

#CXXFLAGS += -g -Wno-deprecated
CXXFLAGS += -O3 -Wno-deprecated

CXXFLAGS += -std=c++20
CXXFLAGS += -I ../
CXXFLAGS += -I props

.include <bsd.prog.mk>
